const GET_CHEAP_FLIGHTS = 'GET_CHEAP_FLIGHTS';
const SET_CHEAP_FLIGHTS = 'SET_CHEAP_FLIGHTS';
const GET_BUSINESS_FLIGHTS='GET_BUISNESS_FLIGHTS';
const SET_BUSINESS_FLIGHTS='SET_BUSINESS_FLIGHTS'

export {  
  GET_CHEAP_FLIGHTS,
  SET_CHEAP_FLIGHTS,
  GET_BUSINESS_FLIGHTS,
  SET_BUSINESS_FLIGHTS
};
